spring.application.name=alert-service

dooray.webhook.url=${DOORAY_HOOK_URL:https://nhnacademy.dooray.com/services/3204376758577275363/4235065872396761556/Idbp2jk4S9ScUbsWAwHe-g}
dooray.webhook.analysis.url=${ALERT_DOORAY_ANALYSIS_URL:https://nhnacademy.dooray.com/services/3204376758577275363/4234906775458915598/Ww0BfzxjTnqbJsR02f41aQ}

server.port=10416

alert.dedup.cooldown=${ALERT_TIMER_MINUTE:10m}
alert.dedup.max-size=${ALERT_DEDUP_MAX_SIZE:100000}

gemini.api-key=${GEMINI_ALERT_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.0-flash-lite}

alert.thread-registry.ttl-minutes: 30
alert.thread-registry.max-size: 100000